spring:
  datasource:
    url: jdbc:h2:mem:service-usage-tracker
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

server:
  port: 8081

usage:
  tracker:
    topic-id: service-usage-tracker-feed